query Categories {
    categories {
        table
        chair
        set
        tableImg {
            url
        }
        chairImg {
            url
        }
        setImg {
            url
        }
    }
}