query Category($id: ID!) {
    category(id: $id) {
        id
        furnitures {
            id
            title
            description
            price
            new
            stock
            img          
        }
    }
}